### ISSUE TITLE
Add Contribution Guide

### ISSUE THREAD

**Issue by stef-codes** [Young-N-Ambitious/.github#1]
Take inspiration from here: https://github.com/github/docs/blob/main/CONTRIBUTING.md

**Comment by kaustav202** [comment]
hi, is the repository participating towards hacktoberfest?.. low-code contributions are allowed

**Comment by kaustav202** [comment]
If so I'd like to work on this

**Comment by stef-codes** [comment]
> If so I'd like to work on this @stef-codes

Yes this is available for Hacktoberfest

**Comment by kaustav202** [comment]
@Sydnee510  @stef-codes  please add the hacktoberfest topic to the repository, otherwise it won't count.

**Comment by AdarshCoder397** [comment]
Hey @kaustav202 , I can work on this!!
